/**
 * Nederlandse veldbeschrijvingen voor de audit trail.
 * Georganiseerd per entityType met een gemeenschappelijke fallback.
 */

const commonLabels: Record<string, string> = {
  // Identificatie
  id: 'ID',
  orgId: 'Organisatie',
  name: 'Naam',
  email: 'E-mailadres',
  phone: 'Telefoon',
  notes: 'Notities',
  description: 'Beschrijving',
  isDeleted: 'Verwijderd',
  isActive: 'Actief',

  // Adresvelden
  street: 'Straat',
  houseNumber: 'Huisnummer',
  postalCode: 'Postcode',
  city: 'Stad',
  country: 'Land',

  // Gebruikersvelden
  firstName: 'Voornaam',
  lastName: 'Achternaam',
  role: 'Rol',

  // Taakvelden
  taskType: 'Taaktype',
};

const entityLabels: Record<string, Record<string, string>> = {
  Contact: {
    type: 'Type',
    companyName: 'Bedrijfsnaam',
    website: 'Website',
    vatNumber: 'BTW-nummer',
    vatValidation: 'BTW-validatie',
    viesNaamOverschreven: 'Naam overschreven via VIES',
    cocNumber: 'KvK-nummer',
    isSupplier: 'Leverancier',
    supplierCustomerNumber: 'Klantnummer (leverancier)',
    purchaseConditions: 'Inkoopvoorwaarden',
    supplierRating: 'Leveranciersbeoordeling',
    priceTableId: 'Prijstabel',
    ownerId: 'Eigenaar',
    customFields: 'Eigen velden',
  },
  ContactPerson: {
    contactId: 'Relatie',
    roleId: 'Rol',
  },
  Location: {
    contactId: 'Relatie',
    locationTypeId: 'Locatietype',
    customFields: 'Eigen velden',
    gebruiksfunctie: 'Gebruiksfunctie',
    bouwjaar: 'Bouwjaar',
    oppervlakte: 'Oppervlakte',
    bagId: 'BAG-ID',
  },
  CustomerGroup: {},
  ProductGroup: {
    notes: 'Notities',
  },
  Product: {
    unit: 'Eenheid',
    defaultVat: 'Standaard BTW',
    productGroupId: 'Productgroep',
    customFields: 'Eigen velden',
  },
  PriceTable: {
    isDefault: 'Standaard',
  },
  PriceTableItem: {
    priceTableId: 'Prijstabel',
    productId: 'Product',
    priceType: 'Prijstype',
    basePrice: 'Basisprijs',
  },
  Request: {
    contactId: 'Relatie',
    locationId: 'Locatie',
    assignedTo: 'Toegewezen aan',
    source: 'Bron',
    status: 'Status',
    title: 'Titel',
    priority: 'Prioriteit',
    lostReasonId: 'Reden verloren',
    lostNote: 'Toelichting verloren',
    createdBy: 'Aangemaakt door',
    customFields: 'Eigen velden',
  },
  Quote: {
    quoteNumber: 'Offertenummer',
    templateId: 'Sjabloon',
    requestId: 'Aanvraag',
    contactId: 'Relatie',
    locationId: 'Locatie',
    status: 'Status',
    subject: 'Onderwerp',
    subtotal: 'Subtotaal',
    discountTotal: 'Korting',
    vatTotal: 'BTW',
    total: 'Totaal',
    validUntil: 'Geldig tot',
    requiresApproval: 'Goedkeuring vereist',
    internalNotes: 'Interne notities',
    createdBy: 'Aangemaakt door',
    customFields: 'Eigen velden',
    pdfStorageKey: 'PDF opslagsleutel',
    signedPdfStorageKey: 'Ondertekende PDF opslagsleutel',
  },
  QuoteLine: {
    quoteId: 'Offerte',
    productId: 'Product',
    quantity: 'Aantal',
    unit: 'Eenheid',
    unitPrice: 'Stukprijs',
    vatRate: 'BTW-tarief',
    discountPct: 'Korting %',
    lineTotal: 'Regeltotaal',
    sortOrder: 'Sortering',
  },
  QuoteTemplate: {
    templateType: 'Sjabloontype',
    defaultValidityDays: 'Standaard geldigheidsdagen',
    requiresApproval: 'Goedkeuring vereist',
    docxFileName: 'DOCX bestandsnaam',
    docxFileSize: 'DOCX bestandsgrootte',
    docxStorageKey: 'DOCX opslagsleutel',
  },
  User: {
    emailVerifiedAt: 'E-mail geverifieerd op',
    color: 'Kleur',
    contactPhone: 'Telefoonnummer klantportaal',
    contactEmail: 'E-mailadres klantportaal',
    sharePhoneWithClients: 'Telefoon tonen in klantportaal',
    shareEmailWithClients: 'E-mail tonen in klantportaal',
    defaultApprovalPersonId: 'Standaard goedkeurder',
  },
  Organization: {
    slug: 'Slug',
    logoUrl: 'Logo URL',
    primaryColor: 'Primaire kleur',
    defaultVat: 'Standaard BTW',
    defaultValidityDays: 'Standaard geldigheidsdagen',
    inspectorPhoneDisplay: 'Telefoon-weergave klantportaal',
    inspectorEmailDisplay: 'E-mail-weergave klantportaal',
    inspectorStaticPhone: 'Statisch telefoonnummer klantportaal',
    inspectorStaticEmail: 'Statisch e-mailadres klantportaal',
    quoteApprovalThreshold: 'Goedkeuringsgrens offertes',
    quoteApprovalRequiredRole: 'Vereiste goedkeur-rol offertes',
    planId: 'Abonnement',
    supportAccessEnabled: 'Support-toegang',
    supportAccessExpiresAt: 'Support-toegang verloopt op',
  },
  Plan: {
    slug: 'Slug',
    sortOrder: 'Sorteervolgorde',
  },
  PlanFeature: {
    planId: 'Abonnement',
    featureKey: 'Functie',
  },
  OrganizationFeature: {
    featureKey: 'Functie',
    enabled: 'Ingeschakeld',
    updatedById: 'Gewijzigd door',
  },
  CustomFieldDefinition: {
    entityType: 'Entiteitstype',
    fieldName: 'Veldnaam',
    label: 'Label',
    fieldType: 'Veldtype',
    options: 'Opties',
    isRequired: 'Verplicht',
    sortOrder: 'Sortering',
  },
  EmailTemplate: {
    type: 'Type',
    name: 'Naam',
    subject: 'Onderwerp',
    bodyJson: 'Inhoud (JSON)',
    bodyHtml: 'Inhoud (HTML)',
    isActive: 'Actief',
    createdBy: 'Aangemaakt door',
  },
  Task: {
    title: 'Titel',
    status: 'Status',
    taskType: 'Taaktype',
    description: 'Omschrijving',
    entityType: 'Gekoppeld type',
    entityId: 'Gekoppeld aan',
    assigneeId: 'Toegewezen aan',
    createdById: 'Aangemaakt door',
    deadline: 'Deadline',
  },
  PlanningItem: {
    status: 'Status',
    contactId: 'Relatie',
    locationId: 'Locatie',
    quoteId: 'Offerte',
    projectId: 'Project',
    productId: 'Product',
    productName: 'Product naam',
    scheduledDate: 'Datum',
    scheduledTime: 'Tijdstip',
    durationMinutes: 'Duur (minuten)',
    labels: 'Labels',
    notes: 'Opmerkingen',
    publicToken: 'Portaal token',
    createdBy: 'Aangemaakt door',
  },
  Project: {
    projectNumber: 'Projectnummer',
    title: 'Titel',
    status: 'Status',
    contactId: 'Relatie',
    locationId: 'Locatie',
    projectManagerId: 'Projectmanager',
    startDate: 'Startdatum',
    expectedEndDate: 'Verwachte einddatum',
    endDate: 'Einddatum',
    createdBy: 'Aangemaakt door',
  },
  ProjectPhase: {
    name: 'Naam',
    description: 'Beschrijving',
    status: 'Status',
    sortOrder: 'Volgorde',
    projectId: 'Project',
    locationId: 'Locatie',
    contactPersonId: 'Contactpersoon',
    startDate: 'Startdatum',
    expectedEndDate: 'Verwachte einddatum',
    completedAt: 'Afgerond op',
    budgetAmount: 'Budget',
    createdBy: 'Aangemaakt door',
  },
  PhaseMilestone: {
    phaseId: 'Fase',
    title: 'Titel',
    description: 'Omschrijving',
    dueDate: 'Streefdatum',
    status: 'Status',
    completedAt: 'Behaald op',
    assigneeId: 'Verantwoordelijke',
    reminderDaysBefore: 'Herinnering (dagen vooraf)',
    sortOrder: 'Volgorde',
  },
  WorkOrder: {
    workOrderNumber: 'Werkbonnummer',
    planningItemId: 'Planregel',
    status: 'Status',
    internalNotes: 'Interne notities',
    startTime: 'Starttijd',
    endTime: 'Eindtijd',
    createdBy: 'Aangemaakt door',
  },
  WorkOrderLine: {
    workOrderId: 'Werkbon',
    productId: 'Product',
    description: 'Omschrijving',
    quantity: 'Aantal',
    unit: 'Eenheid',
    unitPrice: 'Stukprijs',
    vatRate: 'BTW-tarief',
    lineTotal: 'Regeltotaal',
    sortOrder: 'Sortering',
  },
  SupportTicket: {
    ticketNumber: 'Ticketnummer',
    subject: 'Onderwerp',
    status: 'Status',
    priority: 'Prioriteit',
    category: 'Categorie',
    contextModule: 'Module',
    contextUrl: 'Context-URL',
    createdById: 'Aangemaakt door',
    assignedToId: 'Toegewezen aan',
    firstResponseAt: 'Eerste reactie',
    resolvedAt: 'Opgelost op',
    closedAt: 'Gesloten op',
    lastMessageAt: 'Laatste bericht',
  },
};

export function getFieldLabel(entityType: string, field: string): string {
  return (
    entityLabels[entityType]?.[field] ??
    commonLabels[field] ??
    field
  );
}
