import type { Role } from './core';

// ─── PRD-06: Notifications ──────────────────────────────

export enum NotificationType {
  OFFERTE_TER_GOEDKEURING = 'OFFERTE_TER_GOEDKEURING',
  OFFERTE_GOEDGEKEURD = 'OFFERTE_GOEDGEKEURD',
  OFFERTE_AFGEWEZEN = 'OFFERTE_AFGEWEZEN',
  OFFERTE_VERSTUURD = 'OFFERTE_VERSTUURD',
  OFFERTE_BEKEKEN = 'OFFERTE_BEKEKEN',
  OFFERTE_ONDERTEKEND = 'OFFERTE_ONDERTEKEND',
  OFFERTE_VERLOPEN = 'OFFERTE_VERLOPEN',
  NIEUWE_VRAAG_KLANT = 'NIEUWE_VRAAG_KLANT',
  ANTWOORD_OP_VRAAG = 'ANTWOORD_OP_VRAAG',
  AANVRAAG_TOEGEWEZEN = 'AANVRAAG_TOEGEWEZEN',
  AANVRAAG_STATUS_GEWIJZIGD = 'AANVRAAG_STATUS_GEWIJZIGD',
  TAAK_TOEGEWEZEN = 'TAAK_TOEGEWEZEN',
  TAAK_STATUS_GEWIJZIGD = 'TAAK_STATUS_GEWIJZIGD',
  DOCUMENT_GEUPLOAD = 'DOCUMENT_GEUPLOAD',
  AFSPRAAK_ACCEPTATIE_VERZOEK = 'AFSPRAAK_ACCEPTATIE_VERZOEK',
  AFSPRAAK_GEACCEPTEERD = 'AFSPRAAK_GEACCEPTEERD',
  AFSPRAAK_GEWEIGERD = 'AFSPRAAK_GEWEIGERD',
  AFSPRAAK_VERPLAATST = 'AFSPRAAK_VERPLAATST',
  AFSPRAAK_VERZETTEN_VERZOEK = 'AFSPRAAK_VERZETTEN_VERZOEK',
  AFSPRAAK_BEVESTIGING_VERSTUURD = 'AFSPRAAK_BEVESTIGING_VERSTUURD',
  PROJECT_AANGEMAAKT = 'PROJECT_AANGEMAAKT',
  PROJECT_STATUS_GEWIJZIGD = 'PROJECT_STATUS_GEWIJZIGD',
  FOUTMELDING_INGEDIEND = 'FOUTMELDING_INGEDIEND',
  INSPECTIEPLAN_TOEGEWEZEN = 'INSPECTIEPLAN_TOEGEWEZEN',
  INSPECTIEPLAN_TER_REVIEW = 'INSPECTIEPLAN_TER_REVIEW',
  INSPECTIEPLAN_GOEDGEKEURD = 'INSPECTIEPLAN_GOEDGEKEURD',
  INSPECTIEPLAN_AFGEKEURD = 'INSPECTIEPLAN_AFGEKEURD',
  OFFERTE_GOEDKEURING_GEVRAAGD_TEAM = 'OFFERTE_GOEDKEURING_GEVRAAGD_TEAM',
  OFFERTE_GOEDKEURING_GEVRAAGD_PERSOON = 'OFFERTE_GOEDKEURING_GEVRAAGD_PERSOON',
  OFFERTE_GOEDKEURING_AFGEHANDELD = 'OFFERTE_GOEDKEURING_AFGEHANDELD',
  CHAT_BERICHT = 'CHAT_BERICHT',
  CHAT_TEAM_BERICHT = 'CHAT_TEAM_BERICHT',
  CHAT_MENTION = 'CHAT_MENTION',
  SUPPORT_TICKET_AANGEMAAKT = 'SUPPORT_TICKET_AANGEMAAKT',
  SUPPORT_TICKET_REACTIE = 'SUPPORT_TICKET_REACTIE',
  SUPPORT_TICKET_STATUS = 'SUPPORT_TICKET_STATUS',
  MEETMIDDEL_KALIBRATIE_BINNENKORT = 'MEETMIDDEL_KALIBRATIE_BINNENKORT',
  MEETMIDDEL_KALIBRATIE_VERLOPEN = 'MEETMIDDEL_KALIBRATIE_VERLOPEN',
  FASE_STATUS_GEWIJZIGD = 'FASE_STATUS_GEWIJZIGD',
  MILESTONE_HERINNERING = 'MILESTONE_HERINNERING',
  MILESTONE_VERLOPEN = 'MILESTONE_VERLOPEN',
}

export interface Notification {
  id: string;
  orgId: string | null;
  userId: string;
  type: NotificationType;
  title: string;
  body: string;
  entityType: string | null;
  entityId: string | null;
  isRead: boolean;
  readAt: string | null;
  createdAt: string;
}

export interface NotificationPref {
  id: string;
  userId: string;
  notificationType: NotificationType;
  channelInApp: boolean;
  channelEmail: boolean;
}

export interface NotificationGroupPref {
  id: string;
  orgId: string;
  role: Role;
  notificationType: NotificationType;
  channelInApp: boolean;
  channelEmail: boolean;
}

export interface UnreadCountResponse {
  count: number;
}
